apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprintseries
  labels:
    app: sprintseries
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sprintseries
  template:
    metadata:
      labels:
        app: sprintseries
    spec:
      containers:
        - name: sprintseries
          image: aksdevops20220609team02.azurecr.io/sprintseries:v1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: public-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sprintseries